# Generated by Django 3.2 on 2023-09-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=8)),
                ('cv', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=40)),
                ('segundo_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('idioma', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('num_habitacion', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('categoria_habitacion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=2000)),
                ('piso', models.IntegerField()),
                ('precio_dia', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('idNacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('cod_rol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('cargoDetalle', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('num_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_reserva', models.DateTimeField()),
                ('fecha_termino_reserva', models.DateTimeField()),
                ('costo_total', models.DecimalField(decimal_places=0, max_digits=7)),
                ('habitacion_num_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.habitacion')),
                ('habitacion_sucursal_num_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='sucursal_num_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidad_nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nacionalidad'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=8)),
                ('cv', models.CharField(max_length=1)),
                ('primer_nombre', models.CharField(max_length=40)),
                ('segundo_nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('fecha_registro', models.DateTimeField()),
                ('salario', models.DecimalField(decimal_places=0, max_digits=7)),
                ('clave', models.CharField(max_length=100)),
                ('rol_cod_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
                ('sucursal_num_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal')),
            ],
            options={
                'unique_together': {('rol_cod_rol', 'sucursal_num_sucursal')},
            },
        ),
    ]
