# Generated by Django 3.2 on 2023-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
