# Generated by Django 3.2 on 2023-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='cod_rol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
