# Generated by Django 3.2 on 2023-09-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230901_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='sucursal_num_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='rol_cod_rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sucursal_num_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
    ]
